### ISSUE TITLE
Accessing PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by yonatanmn** [mobxjs/mobx-react-devtools#59]
using : 
react-scripts@0.9.5
react@15.5.4
mobx-react-devtools@4.2.11

running npm test - it fails, added trace to fbjs warning, it points at this repo,

``` 

    console.error console.js:89
      Trace: Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
          at printWarning (C:\projects\graphics-gen\node_modules\fbjs\lib\warning.js:36:17)
          at warning (C:\projects\graphics-gen\node_modules\fbjs\lib\warning.js:60:22)
          at Object.get [as PropTypes] (C:\projects\graphics-gen\node_modules\react\lib\React.js:95:49)
          at Object.e.__esModule.default (C:\projects\graphics-gen\node_modules\mobx-react-devtools\index.js:1:21903)
          at t (C:\projects\graphics-gen\node_modules\mobx-react-devtools\index.js:1:589)
          at Object.e.__esModule.default (C:\projects\graphics-gen\node_modules\mobx-react-devtools\index.js:1:14653)
          at t (C:\projects\graphics-gen\node_modules\mobx-react-devtools\index.js:1:589)
          at Object.t.exports (C:\projects\graphics-gen\node_modules\mobx-react-devtools\index.js:1:2868)
          at t (C:\projects\graphics-gen\node_modules\mobx-react-devtools\index.js:1:589)
          at Object.e.__esModule.default (C:\projects\graphics-gen\node_modules\mobx-react-devtools\index.js:1:958)
```

**Comment by OscarBarrett** [comment]
[The fix is in master](https://github.com/mobxjs/mobx-react-devtools/commit/198f753ea2bd9098a3dc044233facb53fdbf81a0), just waiting on release.

**Comment by yonatanmn** [comment]
thx. cool. keeping this open till release?
