### ISSUE TITLE
Uncaught TypeError: Cannot read property 'spy' of undefined

### ISSUE THREAD

**Issue by egorovli** [mobxjs/mobx-react-devtools#64]
Cannot enable extended logging, Chrome version 58.0.3029.110 (64-bit), full error:

```
Uncaught TypeError: Cannot read property 'spy' of undefined
    at t.setGlobalState (eval at ../node_modules/mobx-react-devtools/index.js (http://localhost:8081/dist/js/vendor.js:7411:1), <anonymous>:1:15361)
    at r.handleToggleLog (eval at ../node_modules/mobx-react-devtools/index.js (http://localhost:8081/dist/js/vendor.js:7411:1), <anonymous>:1:29960)
    at Object.ReactErrorUtils.invokeGuardedCallback (eval at ../node_modules/react-dom/lib/ReactErrorUtils.js (http://localhost:8081/dist/js/vendor.js:9837:1), <anonymous>:69:16)
    at executeDispatch (eval at ../node_modules/react-dom/lib/EventPluginUtils.js (http://localhost:8081/dist/js/vendor.js:9382:1), <anonymous>:85:21)
    at Object.executeDispatchesInOrder (eval at ../node_modules/react-dom/lib/EventPluginUtils.js (http://localhost:8081/dist/js/vendor.js:9382:1), <anonymous>:108:5)
    at executeDispatchesAndRelease (eval at ../node_modules/react-dom/lib/EventPluginHub.js (http://localhost:8081/dist/js/vendor.js:9356:1), <anonymous>:43:22)
    at executeDispatchesAndReleaseTopLevel (eval at ../node_modules/react-dom/lib/EventPluginHub.js (http://localhost:8081/dist/js/vendor.js:9356:1), <anonymous>:54:10)
    at Array.forEach (native)
    at forEachAccumulated (eval at ../node_modules/react-dom/lib/forEachAccumulated.js (http://localhost:8081/dist/js/vendor.js:10513:1), <anonymous>:24:9)
    at Object.processEventQueue (eval at ../node_modules/react-dom/lib/EventPluginHub.js (http://localhost:8081/dist/js/vendor.js:9356:1), <anonymous>:257:7)
    at runEventQueueInBatch (eval at ../node_modules/react-dom/lib/ReactEventEmitterMixin.js (http://localhost:8081/dist/js/vendor.js:9850:1), <anonymous>:17:18)
    at Object.handleTopLevel [as _handleTopLevel] (eval at ../node_modules/react-dom/lib/ReactEventEmitterMixin.js (http://localhost:8081/dist/js/vendor.js:9850:1), <anonymous>:28:5)
    at handleTopLevelImpl (eval at ../node_modules/react-dom/lib/ReactEventListener.js (http://localhost:8081/dist/js/vendor.js:9863:1), <anonymous>:72:24)
    at ReactDefaultBatchingStrategyTransaction.perform (eval at ../node_modules/react-dom/lib/Transaction.js (http://localhost:8081/dist/js/vendor.js:10383:1), <anonymous>:140:20)
    at Object.batchedUpdates (eval at ../node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js (http://localhost:8081/dist/js/vendor.js:9785:1), <anonymous>:62:26)
    at Object.batchedUpdates (eval at ../node_modules/react-dom/lib/ReactUpdates.js (http://localhost:8081/dist/js/vendor.js:10149:1), <anonymous>:97:27)
```

**Comment by thiagodebastos** [comment]
I'm getting the same issue:

```
index.js:1 Uncaught TypeError: Cannot read property 'spy' of undefined
    at t.setGlobalState (index.js:1)
    at r.handleToggleLog (index.js:1)
    at HTMLUnknownElement.boundFunc (ReactErrorUtils.js:64)
    at Object.ReactErrorUtils.invokeGuardedCallback (ReactErrorUtils.js:70)
    at executeDispatch (EventPluginUtils.js:78)
    at Object.executeDispatchesInOrder (EventPluginUtils.js:101)
    at executeDispatchesAndRelease (EventPluginHub.js:38)
    at executeDispatchesAndReleaseTopLevel (EventPluginHub.js:49)
    at Array.forEach (<anonymous>)
    at forEachAccumulated (forEachAccumulated.js:26)
	t.setGlobalState	@	index.js:1
    r.handleToggleLog	@	index.js:1
    boundFunc	@	ReactErrorUtils.js:64
    ReactErrorUtils.invokeGuardedCallback	@	ReactErrorUtils.js:70
    executeDispatch	@	EventPluginUtils.js:78
    executeDispatchesInOrder	@	EventPluginUtils.js:101
    executeDispatchesAndRelease	@	EventPluginHub.js:38
    executeDispatchesAndReleaseTopLevel	@	EventPluginHub.js:49
    forEachAccumulated	@	forEachAccumulated.js:26
    processEventQueue	@	EventPluginHub.js:205
    runEventQueueInBatch	@	ReactEventEmitterMixin.js:17
    handleTopLevel	@	ReactEventEmitterMixin.js:28
    handleTopLevelImpl	@	ReactEventListener.js:95
    batchedUpdates	@	ReactFiberScheduler.js:1115
    performFiberBatchedUpdates	@	ReactGenericBatching.js:32
    stackBatchedUpdates	@	ReactGenericBatching.js:23
    batchedUpdates	@	ReactGenericBatching.js:37
    batchedUpdatesWithControlledComponents	@	ReactGenericBatching.js:50
    dispatchEvent
```

Chrome Version 61.0.3127.0 (Official Build) canary (64-bit)
react 16.0.0-alpha.3 (also tried ^15)
react-dom 16.0.0-alpha.3 (also tried ^15)

**Comment by xx7y7xx** [comment]
This demo (https://github.com/mobxjs/mobx-react-todomvc) has the same error:

```
Uncaught TypeError: Cannot read property 'spy' of undefined
    at t.setGlobalState (webpack:///./~/mobx-react-devtools/index.js?:1:15214)
    at r.handleToggleLog (webpack:///./~/mobx-react-devtools/index.js?:1:29813)
    at Object.ReactErrorUtils.invokeGuardedCallback (webpack:///./~/react-dom/lib/ReactErrorUtils.js?:69:16)
    at executeDispatch (webpack:///./~/react-dom/lib/EventPluginUtils.js?:85:21)
    at Object.executeDispatchesInOrder (webpack:///./~/react-dom/lib/EventPluginUtils.js?:108:5)
    at executeDispatchesAndRelease (webpack:///./~/react-dom/lib/EventPluginHub.js?:43:22)
    at executeDispatchesAndReleaseTopLevel (webpack:///./~/react-dom/lib/EventPluginHub.js?:54:10)
    at Array.forEach (native)
    at forEachAccumulated (webpack:///./~/react-dom/lib/forEachAccumulated.js?:24:9)
    at Object.processEventQueue (webpack:///./~/react-dom/lib/EventPluginHub.js?:257:7)
```

**Comment by andykog** [comment]
The error happens because of empty object here https://github.com/mobxjs/mobx/blob/0cfe4a7/src/mobx.ts#L116
I've updated the extension not to throw it that case (will process about an hour), but it won't work until https://github.com/mobxjs/mobx/pull/1041 is released. mobx@3.1.11 should work fine for now.
cc @rossipedia, @mweststrate

**Comment by egorovli** [comment]
@andykog thanks, downgraded mobx to 3.1.11, it works.

**Comment by mweststrate** [comment]
Released in 3.1.15

Op ma 12 jun. 2017 om 09:39 schreef Anton Egorov <notifications@github.com>:

**Comment by rossipedia** [comment]
More module fun! 😒

**Comment by p-adams** [comment]
Is `mobx-react-devtools` not working with the current version of mobx? I am trying to use it but it crashes my app due to the devtools containing undefined variables. Not too sure what the error is.

**Comment by mweststrate** [comment]
Upgrading to mobx 3.1.16 should fix the issue
